name: tf_gpu
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.6.22.post1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numpy=1.19.5
  - pandas=1.1.5
  - python=3.6.15
  - scanpy=1.4.4.post1
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - umap-learn=0.5.1
  - tensorflow-gpu=1.13.1